# 1. NUMPY BASICS

In [99]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np 

# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [100]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [101]:
type(x)

numpy.ndarray

In [102]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [103]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [104]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.44473691, 0.19232374, 0.65124031, 0.12616603, 0.89230524,
       0.29653748, 0.45826365, 0.39740604, 0.62627103, 0.17095494,
       0.929211  , 0.16788092, 0.46779756, 0.29875671, 0.51935101])

In [105]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.6436104 , 0.62561072, 0.80775934, 0.10874623, 0.09703912],
       [0.41407989, 0.91829158, 0.35579875, 0.70657218, 0.04997921],
       [0.43147601, 0.79549803, 0.86904539, 0.95186011, 0.47269712],
       [0.33101837, 0.38216808, 0.12483619, 0.83873573, 0.86848801],
       [0.1924135 , 0.19040241, 0.87235149, 0.44532912, 0.54478421]])

In [106]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 0.73802217,  1.13176863,  1.30833279, -1.37708144,  0.18213021,
        0.97640835, -0.57057218,  0.03761363, -0.7306208 , -0.61812559])

In [107]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

5

In [108]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([12, 20, 19, 66, 27, 41, 35, 31, 25, 45, 35, 66, 51, 21, 91])

In [109]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [110]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [111]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [112]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [114]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [115]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

array([1, 4, 4, 2, 1, 3, 2, 3, 2, 3, 1, 1, 1, 2, 4, 3, 3, 4, 2, 2])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [116]:
# Let's define a one-dimensional array 
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [117]:
# Get Length of a numpy array
len(x)

8

In [118]:
# Get shape
x.shape

(8,)

In [119]:
# Obtain the datatype
matrix.dtype

dtype('int64')

In [120]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
print(x)
print(z)

[-30   4  50  60  29  15  22  90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [121]:
# Obtain the maximum element (value)
x.max()

90

In [122]:
# Obtain the minimum element (value)
x.min()

-30

In [123]:
# Obtain the location of the max element
x.argmax()

7

In [124]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [125]:
x = np.arange(300, 500, 10)
x.shape

(20,)

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [126]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[-415 -139  -43  575  177  789  946  434  948 -581  101 -357 -154 -731
   450  320  947  601 -839  900]
 [-791  276  179   18 -413  487  -41 -547  813  998 -417  163 -186  -26
  -637  869  133 -608 -869  943]
 [ 404  -78  540  155 -268  378  933  124  690  705  146 -950 -674 -311
   102  943 -258 -120 -134 -672]
 [-718 -146 -791  -41  158  985 -800  420  220   19  567 -746 -559 -808
   194  -25  644   59  -77  313]
 [ 730  373  730  -38 -308   17 -808  434 -971  414   27 -820  733 -464
  -323  824 -410  411 -995  853]
 [-572 -407 -126  -51 -969 -530 -979 -494 -511  743  582  -44  927   91
  -249 -311 -906 -151  426  160]
 [-309 -130  676  825  482 -411  611   73   73  881 -255  306  120  528
  -739  130 -830  319  -43 -113]
 [-172   93  966 -845   99 -176 -964 -916 -256 -859 -506 -636  316  189
   827 -236 -579  625  880  289]
 [-779 -311 -826 -955  577  -74 -204  133  186  299 -734 -899  414 -796
  -800 -280  716 -876  517 -712]
 [-716  188  727  -38  290  718 -539 -746 -129 -644 -56

# 4. MATHEMATICAL OPERATIONS

In [127]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [130]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [131]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [133]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [134]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [135]:
# Access specific index from the numpy array
x[0]

20

In [136]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [137]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [138]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[6, 1, 3, 3, 4],
       [2, 3, 2, 4, 1],
       [1, 8, 4, 9, 7],
       [1, 9, 4, 9, 3],
       [7, 3, 9, 4, 9]])

In [139]:
# Get a row from a mtrix
matrix[2]

array([1, 8, 4, 9, 7])

In [140]:
# Get one element
matrix[0][2]

3

In [141]:
mini_matrix = matrix[:3]
mini_matrix

array([[6, 1, 3, 3, 4],
       [2, 3, 2, 4, 1],
       [1, 8, 4, 9, 7]])

In [142]:
mini_matrix = matrix[2:]
mini_matrix

array([[1, 8, 4, 9, 7],
       [1, 9, 4, 9, 3],
       [7, 3, 9, 4, 9]])

In [143]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[6, 1],
       [2, 3],
       [1, 8],
       [1, 9],
       [7, 3]])

In [144]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[3, 3, 4],
       [2, 4, 1],
       [4, 9, 7],
       [4, 9, 3],
       [9, 4, 9]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [145]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [146]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [147]:
X[:2, 3:]  = X[:2, 3:] * 2
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [148]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[4, 5, 2, 7, 7],
       [2, 4, 6, 7, 3],
       [6, 6, 1, 2, 8],
       [8, 8, 8, 5, 8],
       [9, 4, 4, 4, 5]])

In [149]:
new_matrix = matrix[matrix>3]
new_matrix

array([4, 5, 7, 7, 4, 6, 7, 6, 6, 8, 8, 8, 8, 5, 8, 9, 4, 4, 4, 5])

In [150]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([4, 2, 2, 4, 6, 6, 6, 2, 8, 8, 8, 8, 8, 4, 4, 4])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [151]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])